### ISSUE TITLE
Using data in Processing

### ISSUE THREAD

**Issue by andrejilderda** [microcosm/KinectV2-OSC#3]
Hi Andrew,

I've got KinectV2OSC working on a Windows machine, nice! I'm now trying to get the OSC messages into Processing with the [oscP5](http://www.sojamo.de/libraries/oscP5/) library. The data I already receive in the Processing sketch on a Mac, but unfortunately don't know where to begin from there. Would you consider an equivalent of ofxKinectV2-OSC for Processing?

Best,
Andre

**Comment by microcosm** [comment]
Hi, that sounds great but unfortunately I won't have time to do it.
