### ISSUE TITLE
Send to custom

### ISSUE THREAD

**Issue by ShadowMitia** [microcosm/KinectV2-OSC#4]
Hello, 

Is there a way to change the port value to which data is sent?
Is there an easy way to change the port number for a specific IP?

Thanks

**Comment by microcosm** [comment]
Check the readme: https://github.com/microcosm/KinectV2-OSC

The bit that says "To send to another destination, change the IP and port number here, and then re-launch"

**Comment by microcosm** [comment]
You have to compile from source to do that though
