### ISSUE TITLE
monitor OSC data

### ISSUE THREAD

**Issue by evovinetu** [microcosm/KinectV2-OSC#9]
I'm trying to get skeleton data from Kinect v2 via OSC to EyesWeb project.
When i open KinectV2OSC, it shows that connection is established, i see the skeleton.
But EyesWeb doesn't pick up any data from the port 12345.

[OSC Data Monitor](https://github.com/kasperkamperman/OSCDataMonitor)  also doesn't show any activity in port 12345.

Is there another way to check, if OSC data is really streaming from KinectV2OSC?

System: Windows 10, x64.

**Comment by Raznyy** [comment]
I'm having the same issue. I try to recive data in different monitors but with no effects at all.
I also tried to debug difectly from WSE 2013 for Windows Desktop and I came to see that data is getting sended but no chance to recive it anywhere.
Anyone have some solutions for that? Is it about Windows version? I'm working on 10  64x

Any help will be appreciated

**Comment by evovinetu** [comment]
In Command Prompt, if i run "netstat -a -n", i see that port's 1234 local address is not 127.0.0.1 but 0.0.0.0:
`Active Connections`
` Proto  Local Address          Foreign Address        State`
` UDP    0.0.0.0:12345          *:*`

Could that be the problem?

**Comment by evovinetu** [comment]
I tried it on Windows 8.1 x64, no luck.

BUT i found a working alternative!!!
[https://github.com/rwebber/kinect2share](https://github.com/rwebber/kinect2share)

**Comment by microcosm** [comment]
Glad to hear it! Yes this project is currently unmaintained. Glad you found the alternative.
